CREATE DATABASE uploaderdb;
CREATE ROLE user1 WITH CREATEDB LOGIN;
CREATE SCHEMA IF NOT EXISTS uj;
GRANT USAGE ON SCHEMA uj TO user1;
GRANT ALL PRIVILEGES ON DATABASE uploaderdb TO user1;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA uj TO user1;