news-bus:
    producer:
        server: localhost:9092
        serverPort: 9092
        batchSize: 16384
        bufferMemory: 33554432
kafka:
    flush:
        timeoutSeconds: 5
        maxTries: 3

topics:
    newsBus: "topic_test"